# -*- coding: utf-8 -*-
"""summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkhGG4eGPbL5CZTCiU1bRLPvlaK4yVnz
"""

import streamlit as st
from langchain import OpenAI
from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.summarize import load_summarize_chain

def generate_response(txt):
    openai_api_key="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"
    llm = OpenAI(temperature=0, openai_api_key=openai_api_key)
    text_splitter = CharacterTextSplitter()
    texts = text_splitter.split_text(txt)
    docs = [Document(page_content=t) for t in texts]
    chain = load_summarize_chain(llm, chain_type='map_reduce')
    return chain.run(docs)

st.set_page_config(page_title='Text Summarization')
st.title('Text Summarization')

txt_input = st.text_area('Enter text to summarize', '', height=200)

result = []
submitted = st.button('Submit')
if submitted:
	with st.spinner('Summarizing...'):
		response = generate_response(txt_input)
		result.append(response)

if len(result):
    st.info(response)
